### ISSUE TITLE
Test different OS

### ISSUE THREAD

**Issue by tpilz** [tpilz/lumpR#1]
Package developed on Linux opensuse 13.1 and GRASS 6.4.3.

Should be tested for (at least) Windows and MAC.

**Comment by TillF** [comment]
Related issues in https://github.com/tpilz/LUMP/issues/10, https://github.com/tpilz/LUMP/issues/11 and https://github.com/tpilz/LUMP/issues/12

**Comment by TillF** [comment]
only #12 remaining, closed.
