### ISSUE TITLE
parameter database: correcting fractions  of entities (normalization)

### ISSUE THREAD

**Issue by TillF** [tpilz/lumpR#20]
The current praxis in "filter_small_areas" drops the respective tables and uploads the corrected ones.
Fine with me, but this will probably violate constraints/relations - do you still use them anywhere. 
If so, using the SQL-queries in my lates version of database.R may be the better option to do the correction.

**Comment by tpilz** [comment]
So far we agreed that no relations or constraints will be implemented as db_check() implicitly includes functionalities of these. Furthermore, support of different DBMS make implementation of relations more complicated.
