### ISSUE TITLE
first steps: install_github

### ISSUE THREAD

**Issue by jmigueldelgado** [tpilz/lumpR#24]
not sure if this is general to all versions of devtools, but while installing in the cluster, the following syntax was not accepted:

install_github("https://github.com/tpilz/LUMP")

This was accepted though:

install_github("tpilz/LUMP")

**Comment by tpilz** [comment]
you are right, this is wrong in the example file `LUMP_main.R`. I'll fix this. In Wiki and README it is correct, though.

Tank you!
