### ISSUE TITLE
calc_subbas(): Single flow vs. Multiple flow algorithm

### ISSUE THREAD

**Issue by tpilz** [tpilz/lumpR#26]
At the moment for subbasin delineation using the GRASS function r.watershed the single flow direction (SFD) algorithm is used. In literature it is usually stated that multiple flow direction (MFD) algorithm should be superior. In my tests, however, when employing MFD, (still using GRASS 6.4.5) there have been problems as the generated flow accumulation map diverges at some points (causing trouble with the identification of river cells and catchment outlets) and generated subbasins are more variable in size.

One could think a litter deeper on that problem. So far I decided to use the SFD algorithm.

**Comment by TillF** [comment]
MFD may be superior in the sense that it allows the more natural representation of flow, especially in flat areas. However, as the concept of subbasins requires a unique membership to a single subbasin, I suppose there is not too much benefint in using MFD for that. In flat areas, thre true hydrological catchment may be determined by features invisible in the DEM anyway, so whoever wants to get this right, may have to do so manually.
