### ISSUE TITLE
write a wiki

### ISSUE THREAD

**Issue by tpilz** [tpilz/lumpR#4]
Write a wiki at github.

**Comment by TillF** [comment]
I extended the existing wiki to some degree.
Can we run a user mailing list or forum to collect FAQs publicly? Or should be make this a part of the Wiki?

**Comment by tpilz** [comment]
Thanks a lot, that makes things more easy to new users.

To have everything more centralized I would prefer to have the FAQ section included in the Wiki.

**Comment by tpilz** [comment]
better write vignettes covering different topics, see #51
