### ISSUE TITLE
db_compute_musleK extra options

### ISSUE THREAD

**Issue by A-Mue** [tpilz/lumpR#48]
Wish list of additional features:
- option to automatically set musle_p to 1, if desired
- automatically copy (from "horizons.dat"), column "coarse_frag" for 1st soil horizon into data base table "soil_veg_components", column "coarse_frac"
- inconsistent nomenclature of "horizons.dat" column "coarse_frag" and "svc.dat" column "coarse_frac" ?

**Comment by TillF** [comment]
- copy MUSLE-C and Manning n from table "vegetation"
