### ISSUE TITLE
Problem with installation of lumpR

### ISSUE THREAD

**Issue by allayur** [tpilz/lumpR#50]
On a latest version of RGui and Rtools running on Windows 10 x64 machine I can not install the current version of lumpR 
Error massage is the following 
Error: package or namespace load failed for 'lumpR' in namespaceExport(ns, exports): undefined exports: db_compute_musleK
I use the standart set of commands from command line of RGui
install.packages("devtools") 
library(devtools)
install_github("tPilz/lumpR")

**Comment by tpilz** [comment]
Thanks for trying lumpR!

This must be related to the latest commits. Until it is fixed, please try `devtools::install_github("tpilz/lumpR@v3.0.0")`.

@TillF Looks like there is a bug in the NAMESPACE file.

**Comment by allayur** [comment]
Thanks a lot, Tobias!
It solved the issue (this version installs and works fine)
