### ISSUE TITLE
Classified catena output

### ISSUE THREAD

**Issue by allayur** [tpilz/lumpR#54]
Could you please provide the txt output with partitioning class (x-distance, y-relative elevation gain) for each catena of the resulting classes that are currently printed to the final section of plots_prof_class.pdf. This is needed for direct  processing in the code different from WASA model

**Comment by TillF** [comment]
Did you have a look at lu.dat? It contains the final resulting shape of each toposequence, its horizontal and vertical extent and the partitioning.

**Comment by allayur** [comment]
Thanks-I found it now! Could you please inform how to convert 1) elevation and 2) slope width from the units in the lu.dat to the absolute values (m)?

**Comment by TillF** [comment]
I've added a description to the help file, but currently cannot get it compiled, so I paste it here:

#'      \bold{Landscape units properties parameters}\cr
#'		The file \code{luoutfile} contains the properties of the resulting landscape units (i.e. their representative toposequence) and is later imported into the WASA-database with \code{\link[lumpR]{db_fill}}. 
#'      \emph{LU-ID}\cr
#'      ID of resulting landscape unit / class. For 'successive' classification, the digits of the ID may reflect the classification according to the involved attributes (i.e. '143' corresponding to class 1, 4 and 3 for attributes 1, 2 and 3, respectively).
#'      \emph{closest_catena}\cr
#'      ID of EHA / catena most similar to the resulting toposequence of the LU. Should only be used with 'singlerun' classification.
#'      \emph{closest_dist}\cr
#'      Distance of closest catena to cluster centre. Should only be used with 'singlerun' classification.
#'      \emph{x_length}\cr
#'      Horizontal extent of toposequence in map units.
#'      \emph{y_length}\cr
#'      Vertical extent of toposequence in z-units of DEM.
#'      \emph{lim_var<ntc-1>}\cr
#'      Index of toposequence points (see ...) that are the resulting borders of the <ntc> TCs, resulting from minimizing intra-TC variance.
#'      \emph{lim_clu<ntc-1>}\cr
#'      Index of toposequence points (see ...) that are the resulting borders of the <ntc> TCs, resulting from within-TC-cluster analysis (currently not used in further steps).
#'      \emph{<attribute>_p<1..com_length>}\cr
#'      \code{com_length} contains the number of points, to which all catenas and toposequences were resampled. Thus, the corresponding number of columns are used for each attribute to specify its value at this point. For example, 'LAI_p1' reporesents the value at the very foot of the catena, LAI_p<com_length> the point at the end of the toposequence, i.e. at \code{x_length}. If <attribute> is categorical, <attribute>_p<#point>_c<#class> denotes the fraction of class '#class' at point '#point'.
#'

**Comment by allayur** [comment]
Thank you for the help file. However, one question is still there. If I, for example, have slope_width = 0.02 in lu.dat file, how can I get slope_width in map units?

**Comment by tpilz** [comment]
Actually this is not reflecting real width, but can be interpreted as a proxy. More information can be obtained from [Till's original LUMP paper](https://www.tandfonline.com/doi/full/10.1080/13658810701300873), section 2.2.3.3. Only there the cumulative value is described, while in the file the densitiy value is given. I.e. it always sums up to one for every EHA. In `area2catena()` it is calculated as the number of raster cells for a certain EHA point (i.e. distance to river) divided by the total number of cells of that EHA.

I think it is not possible to translate the relative into absolute values.

**Comment by TillF** [comment]
Thanks Tobias, for explaining the matter. As he pointed out, this is more of a proxy. 
If you really need a metric number, you could compute the average size A of all correspondingly EHAs. From lu.dat, you have the along-slope length L. Thus, the average width W would be W=A/L. Multiplying W with the proxy slope normalized to unity would give some metric measure. I am not sure if it is very meaningful, though.
